apiVersion: v1
kind: Service
metadata:
  name: colocacoes-scrapper-service
spec:
  selector:
    app: colocacoes-scrapper
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: colocacoes-scrapper-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: colocacoes-scrapper
  template:
    metadata:
      labels:
        app: colocacoes-scrapper
    spec:
      containers:
      - name: colocacoes-scrapper
        image: crawlingcity/colocacoes-scrapper:x64
        ports:
        - containerPort: 5000
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: colocacoes-scrapper-ingressroute
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`www.colocacoes.crawlingcity.com`)
      kind: Rule
      services:
        - name: colocacoes-scrapper-service
          port: 80
    - match: Host(`colocacoes.crawlingcity.com`)
      kind: Rule
      services:
        - name: colocacoes-scrapper-service
          port: 80
  tls:
    secretName: local-crawlingcity-com-tls

